name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: v16
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm i && cd packages/schema-org && pnpm build
      - run: cd packages/vite && pnpm build
      - run: cd ./test/fixtures/nuxt/ && pnpm install && pnpm nuxt:prepare

      - name: PNPM build
        run: pnpm run build

      - name: Publish to NPM
        run: pnpm -r publish --access public --no-git-checks --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Release Notes
        run: npx changelogen@latest > ${{ github.workspace }}-CHANGELOG.md

      - name: Trim Release Notes and debug
        run: sed -i '1d;2d' ${{ github.workspace }}-CHANGELOG.md && cat ${{ github.workspace }}-CHANGELOG.md

      - name: Push release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.md
